name: jpl_programmation_crud
description: A new Flutter package project.
version: 0.0.2
homepage:

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  crypto: ^3.0.2
  flutter:
    sdk: flutter
  http: ^1.2.1
  intl: ^0.19.0
  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
