
const List<String> constListeProvinceCan = [
  "Alberta",
  "Colombie-Britannique",
  "Île-du-Prince-Édouard",
  "Manitoba",
  "Nouveau-Brunswick",
  "Nouvelle-Écosse",
  "Nunavut",
  "Ontario",
  "Québec",
  "Saskatchewan",
  "Terre-Neuve-et-Labrador",
  "Territoires du Nord-Ouest",
  "Yukon",
];

const List<String> constListePays = [
  "Afghanistan",
  "Afrique du Sud",
  "Albanie",
  "Algérie",
  "Allemagne",
  "Andorre",
  "Angola",
  "Anguilla",
  "Antarctique",
  "Antigua-et-Barbuda",
  "Antilles Néerlandaises",
  "Arabie Saoudite",
  "Argentine",
  "Arménie",
  "Aruba",
  "Australie",
  "Autriche",
  "Azerbaïdjan",
  "Bahamas",
  "Bahreïn",
  "Bangladesh",
  "Barbade",
  "Bélarus",
  "Belgique",
  "Belize",
  "Bénin",
  "Bermudes",
  "Bhoutan",
  "Bolivie",
  "Bosnie-Herzégovine",
  "Botswana",
  "Brésil",
  "Brunéi Darussalam",
  "Bulgarie",
  "Burkina Faso",
  "Burundi",
  "Cambodge",
  "Cameroun",
  "Canada",
  "Cap-vert",
  "Chili",
  "Chine",
  "Chypre",
  "Colombie",
  "Comores",
  "Costa Rica",
  "Côte d Ivoire",
  "Croatie",
  "Cuba",
  "Danemark",
  "Djibouti",
  "Dominique",
  "Égypte",
  "El Salvador",
  "Émirats Arabes Unis",
  "Équateur",
  "Érythrée",
  "Espagne",
  "Estonie",
  "États Fédérés de Micronésie",
  "États-Unis",
  "Éthiopie",
  "Fédération de Russie",
  "Fidji",
  "Finlande",
  "France",
  "Gabon",
  "Gambie",
  "Géorgie",
  "Géorgie du Sud et les Îles Sandwich du Sud",
  "Ghana",
  "Gibraltar",
  "Grèce",
  "Grenade",
  "Groenland",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guinée",
  "Guinée Équatoriale",
  "Guinée-Bissau",
  "Guyana",
  "Guyane Française",
  "Haïti",
  "Honduras",
  "Hong-Kong",
  "Hongrie",
  "Île Bouvet",
  "Île Christmas",
  "Île de Man",
  "Île Norfolk",
  "Îles (malvinas) Falkland",
  "Îles Åland",
  "Îles Caïmanes",
  "Îles Cocos (Keeling)",
  "Îles Cook",
  "Îles Féroé",
  "Îles Heard et Mcdonald",
  "Îles Mariannes du Nord",
  "Îles Marshall",
  "Îles Mineures Éloignées des États-Unis",
  "Îles Salomon",
  "Îles Turks et Caïques",
  "Îles Vierges Britanniques",
  "Îles Vierges des États-Unis",
  "Inde",
  "Indonésie",
  "Iraq",
  "Irlande",
  "Islande",
  "Israël",
  "Italie",
  "Jamahiriya Arabe Libyenne",
  "Jamaïque",
  "Japon",
  "Jordanie",
  "Kazakhstan",
  "Kenya",
  "Kirghizistan",
  "Kiribati",
  "Koweït",
  "L ex-République Yougoslave de Macédoine",
  "Lesotho",
  "Lettonie",
  "Liban",
  "Libéria",
  "Liechtenstein",
  "Lituanie",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malaisie",
  "Malawi",
  "Maldives",
  "Mali",
  "Malte",
  "Maroc",
  "Martinique",
  "Maurice",
  "Mauritanie",
  "Mayotte",
  "Mexique",
  "Monaco",
  "Mongolie",
  "Montserrat",
  "Mozambique",
  "Myanmar",
  "Namibie",
  "Nauru",
  "Népal",
  "Nicaragua",
  "Niger",
  "Nigéria",
  "Niué",
  "Norvège",
  "Nouvelle-Calédonie",
  "Nouvelle-Zélande",
  "Oman",
  "Ouganda",
  "Ouzbékistan",
  "Pakistan",
  "Palaos",
  "Panama",
  "Papouasie-Nouvelle-Guinée",
  "Paraguay",
  "Pays-Bas",
  "Pérou",
  "Philippines",
  "Pitcairn",
  "Pologne",
  "Polynésie Française",
  "Porto Rico",
  "Portugal",
  "Qatar",
  "République Arabe Syrienne",
  "République Centrafricaine",
  "République de Corée",
  "République de Moldova",
  "République Démocratique du Congo",
  "République Démocratique Populaire Lao",
  "République Dominicaine",
  "République du Congo",
  "République Islamique d Iran",
  "République Populaire Démocratique de Corée",
  "République Tchèque",
  "République-Unie de Tanzanie",
  "Réunion",
  "Roumanie",
  "Royaume-Uni",
  "Rwanda",
  "Sahara Occidental",
  "Saint-Kitts-et-Nevis",
  "Saint-Marin",
  "Saint-Pierre-et-Miquelon",
  "Saint-Siège",
  "Saint-Vincent-et-les Grenadines",
  "Sainte-Hélène",
  "Sainte-Lucie",
  "Samoa",
  "Samoa Américaines",
  "Sao Tomé-et-Principe",
  "Sénégal",
  "Serbie-et-Monténégro",
  "Seychelles",
  "Sierra Leone",
  "Singapour",
  "Slovaquie",
  "Slovénie",
  "Somalie",
  "Soudan",
  "Sri Lanka",
  "Suède",
  "Suisse",
  "Suriname",
  "Svalbard etÎle Jan Mayen",
  "Swaziland",
  "Tadjikistan",
  "Taïwan",
  "Tchad",
  "Terres Australes Françaises",
  "Territoire Britannique de l Océan Indien",
  "Territoire Palestinien Occupé",
  "Thaïlande",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinité-et-Tobago",
  "Tunisie",
  "Turkménistan",
  "Turquie",
  "Tuvalu",
  "Ukraine",
  "Uruguay",
  "Vanuatu",
  "Venezuela",
  "Viet Nam",
  "Wallis et Futuna",
  "Yémen",
  "Zambie",
  "Zimbabwe"
];

const String pays = 'Pays';
const String province = 'Province';
const String codePostal = 'Code Postal';
const String ville = 'Ville';
const String rue = 'Rue';
const String numeroCivique = 'Numéro Civique';
const String appartement = 'Appartement$optionnel';
const String optionnel = ' (optionnel)';

const String entrezPays = 'Entrez un pays';
const String entrezProvince = 'Entrez une province';
const String entrezCodePostal = 'Entrez un code postal';
const String entrezVille = 'Entrez une ville';
const String entrezRue = 'Entrez une rue';
const String entrezNumeroCivique = 'Entrez un numéro civique';